We can also solve linear equations using matrices. If we want to build a portfolio of securities, and the allocation must meet constraints, then we can solve to find the amount.

$$2a + b + c = 4$$
$$a + 3b + 2c= 5$$
$$a = 6$$

In [2]:
import numpy as np
A = np.array([[2,1,1],
             [1,3,2],
             [1,0,0]])
B = np.array([4,5,6])

print(np.linalg.solve(A,B))

[  6.  15. -23.]


This means that we would need long positions of 6 units for a and 15 units for b, and a short position of 23 units for c.
However, using matrices for large amounts of variables (securities) can become computationally exepnsive, so there are various methods for breaking the matrix into simpler ones for factorisation.

<h1>LU decomposition</h1>

Lower upper factorisation - solve square systems of linear equations. It decomposes a matrix into a lower triangular matrix and an upper triangular matrix.

$\begin{bmatrix}
    a&b&c\\
    d&e&f\\
    g&h&i
\end{bmatrix}$
$=$
$\begin{bmatrix}
    l_{11}&0&0\\
    l_{21}&l_{22}&0\\
    l_{31}&l_{32}&l_{33}
\end{bmatrix}$
$*$
$\begin{bmatrix}
    l_{11}&l_{12}&l_{13}\\
    0&l_{22}&l_{23}\\
    0&0&l_{33}
\end{bmatrix}$

In [5]:
import scipy.linalg
LU = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve(LU, B)
print(x)

[  6.  15. -23.]


<h1>Cholesky decomposition</h1>

This can be a faster way of solving systems of linear equations by exploiting symmetric matrices. However, the matrix being decomposed needs to be Hermitian. This means that it must be real-valued symmetric/square. It also must be a positive definite.
We can use the following example:

$A = \begin{bmatrix}
    10&-1&2&0\\
    -1&11&-1&3\\
    2&-1&10&-1\\
    0&3&-1&8\\
\end{bmatrix}$
$, x = $
$\begin{bmatrix}
    a\\
    b\\
    c\\
    d\\
\end{bmatrix}$
$, B = $
$\begin{bmatrix}
    6\\
    25\\
    -11\\
    15\\
\end{bmatrix}$

In [10]:
import numpy as np
A = np.array([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,-1],[0,3,-1,8]])
B = np.array([6,25,-11,15])
L = np.linalg.cholesky(A)

print("L:")
print(L)
#You can verify that this is correct by multiplying L with the conjugate transpose
print("verification:")
print(np.dot(L,L.T.conj()))
#Solve for L^T x:
print("Y:")
y = np.linalg.solve(L,B)
print(y)
#solve for x by solving again using conjugate transpose
print("X:")
x = np.linalg.solve(L.T.conj(), y)
print(x)

L:
[[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.08889696  0.        ]
 [ 0.          0.9086738  -0.25245792  2.6665665 ]]
verification:
[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]
Y:
[ 1.8973666   7.75401642 -3.34135488  2.6665665 ]
X:
[ 1.  2. -1.  1.]
